baseURL = "https://aagat.com/"
languageCode = "en-us"
title = "Aagat Adhikari"
theme = "default"

pygmentsUseClasses=true
pygmentsCodeFences=true

enableRobotsTXT = true

[params]
    author = "Aagat Adhikari"
    description = "Aagat Adhikari - Software Developer"
    keywords = "Aagat, Aagat Adhikari, Software Developer, Programmer, Nepal"